// General Information
const SET_GEN_INFO = 'SET_GEN_INFO';

// Contacts
const SET_CONTACTS = 'SET_CONTACTS';

// Registration Address
const SET_REG_ADDRESS = 'SET_REG_ADDRESS';

// Actual Location Address
const SET_ACT_LOC_ADDRESS = 'SET_ACT_LOC_ADDRESS';

// Education Status
const SET_EDUCATION_STATUS = 'SET_EDUCATION_ADDRESS';

// Employment
const SET_EMPLOYMENT = 'SET_EMPLOYMENT';

// Main Place of Work
const SET_MAIN_PLACE_WORK = 'SET_MAIN_PLACE_WORK';

// Monthly Income
const SET_MONTHLY_INCOME = 'SET_MONTHLY_INCOME';

// Credit Parameters
const SET_CREDIT_PARAMETERS = 'SET_CREDIT_PARAMETERS';

export {
    SET_GEN_INFO,
    SET_CONTACTS,
    SET_REG_ADDRESS,
    SET_ACT_LOC_ADDRESS,
    SET_EDUCATION_STATUS,
    SET_EMPLOYMENT,
    SET_MAIN_PLACE_WORK,
    SET_MONTHLY_INCOME,
    SET_CREDIT_PARAMETERS,
};
