export const initialState = [
    {
        id: 'generalInformation',
        fullName: '',
        prevName: '',
        citizenship: '',
        gender: '',
        bankruptcy: '',
        birthDay: '',
        placeOfBirth: '',
        passport: '',
        codeDepartment: '',
        dateOfPassport: '',
        issuingAuthority: '',
    },
    {
        id: 'contacts',
        phone: '',
        additionalPhone: '',
        email: '',
    },
    {
        id: 'registrationAddress',
        postCode: '',
        region: '',
        city: '',
        street: '',
        houseNumber: '',
        houseBuilding: '',
        apartment: '',
    },
    {
        id: 'actualLocationAddress',
        actualPostcode: '',
        actualRegion: '',
        actualCity: '',
        actualStreet: '',
        actualHouseNumber: '',
        actualHouseBuilding: '',
        actualApartmentNumber: '',
        livingTimeRegion: '',
    },
    {
        id: 'educationStatus',
        dependent: '',
        educationStatus: '',
        familyStatus: '',
    },
    {
        id: 'employment',
        totalWorkExperience: '',
    },
    {
        id: 'mainPlaceOfWork',
        organizationName: '',
        taxNumber: '',
        webSite: '',
        workPhone: '',
        workAddress: '',
        chief: '',
        typeOwnership: '',
        typeActivities: '',
        typePositionHeld: '',
        workExperiencePositionHeld: '',
    },
    {
        id: 'moonthlyIncome',
        income: '',
        addIncome: '',
        pension: '',
        otherIncome: '',
    },
    {
        id: 'creditParameters',
        creditSum: '',
        creditTerm: '',
        insuranceСonsent: '',
    },
];
